services:
    backend:
        build:
            context: ./backend
        container_name: manage-yukikaki-backend
        environment:
            SECRET_KEY: ${SECRET_KEY:-devsecret}
        volumes:
            - ./backend/src/db:/app/db
        restart: unless-stopped
        networks:
            - manage-yukikaki-net

    frontend:
        build:
            context: ./frontend
        container_name: manage-yukikaki-frontend
        depends_on:
            - backend
        environment:
            BACKEND_URL: ${FRONTEND_BACKEND_URL:-https://api.mng-yukikaki.rhappy.dev}
        restart: unless-stopped
        networks:
            - manage-yukikaki-net

networks:
    manage-yukikaki-net:
        external: true
