services:
    backend:
        build:
            context: ./backend
        container_name: manage-yukikaki-backend
        environment:
            SECRET_KEY: ${SECRET_KEY:-devsecret}
        ports:
            - "1323:1323"
        volumes:
            - ./backend/src/db:/app/db
        restart: unless-stopped

    frontend:
        build:
            context: ./frontend
        container_name: manage-yukikaki-frontend
        depends_on:
            - backend
        environment:
            BACKEND_URL: ${FRONTEND_BACKEND_URL:-http://localhost:1323}
        ports:
            - "8080:4200"
        restart: unless-stopped
